algo = input('Digite algo: ')
print('O tipo primitivo deste valor é ', type(algo))
print('Só tem espacos ? ', algo.isspace())
print('É um número ? ', algo.isnumeric())
print('É um alfabético ? ', algo.isalnum())
print('É um alphanumérico ?', algo.isalpha())
print('Está em maiúsculo ? ', algo.isupper())
print('Está em minusculo ? ', algo.islower())
print('Está em capitalizado ? ', algo.istitle())

